#spring配置
spring:
  datasource:
    #配置druid数据源
    druid:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      url: jdbc:sqlserver://116.204.97.73:1433;database=db_atm
      username: sa
      password: Tsm20045324

  #修改时区配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


#端口配置
server:
  port: 8081

#mybatis配置
#mybatis:
#  mapper-locations: classpath:mappers/*xml

